services:
  bet_maker_backend:
    platform: linux/amd64
    container_name: bet_maker_backend
    build:
      dockerfile: Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=Europe/Moscow
    restart: always
    networks:
      - bet_maker_network
    depends_on:
      bet_maker_db:
        condition: service_healthy
    command: ./entrypoint.sh
    ports:
      - 8000:8000

  bet_maker_db:
    image: postgres:15.4
    shm_size: 256m
    platform: linux/amd64
    container_name: bet_maker_db
    networks:
      - bet_maker_network
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

networks:
  bet_maker_network:
    driver: bridge
    ipam:
      driver: default
