"""create_tables

Revision ID: 90bc824cf052
Revises: 
Create Date: 2024-03-27 23:12:42.020319

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "90bc824cf052"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bet",
        sa.Column("event_id", sa.VARCHAR(length=64), nullable=False),
        sa.Column("summa", sa.NUMERIC(precision=10, scale=2), nullable=False),
        sa.Column(
            "status",
            sa.Enum("LOSE", "WIN", "NOT_PLAYED", name="betstatus"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("bet")
    # ### end Alembic commands ###
